language: c

sudo: false

install:
    - sudo apt-get install luarocks
    - sudo apt-get install lua-bitop
    - sudo luarocks install busted
    - sudo luarocks install moonscript
    - sudo luarocks install ldoc

script:
    - busted
    - ldoc .
